### PR TITLE
Remove `master` branch references after migrating to `main`

### LINKED ISSUE #318: Remove `master` branch references after migrating to `main`
This issue highlights a need to remove remaining mentions of the `master` branch after migrating to use `main` instead. Some of the discussion on this topic occurred via https://github.com/cytomining/pycytominer/pull/303#discussion_r1283814743 . Both `master` and `main` were provided in the merged work found in #303 to help with this transition.

### PR DESCRIPTION
**Pull request by kenibrewer**
Fixes #318

# Description

As part of the transition to more inclusive language this removes references to the `master` branches that were previously present in the codebase. 

## What is the nature of your change?

- [X] Bug fix (fixes an issue).

# Checklist

Please ensure that all boxes are checked before indicating that a pull request is ready for review.

- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have deleted all non-relevant text in this pull request template.

### CODE REVIEW

**Comment by kenibrewer** [comment]
@d33bs Could I request a review on this please? Thanks!

**Review by d33bs — APPROVED** [review]
This LGTM, thank you @kenibrewer ! 

As an aside, I think it might be good to double check the config under https://readthedocs.org/projects/pycytominer/ to make sure it references `main` moving forward. @gwaybio , do you know if we're able to change what branch or reference URL is used for documentation there?

**Comment by gwaybio** [comment]
> do you know if we're able to change what branch or reference URL is used for documentation there?

Done! Changed to `main` in RTD. Docs are passing!

**Comment by gwaybio** [comment]
Thanks @kenibrewer !

**Pull request merged**
