### PR TITLE
Update python versions - 3.7 deprecation, 3.10 and 3.11 testing support

### PR DESCRIPTION
**Pull request by gwaybio**
# Description

With [python 3.7 security end of life in 2 weeks](https://endoflife.date/python), this update is required prior to version 1 release. This also addresses #259.

## What is the nature of your change?

- [ ] Bug fix (fixes an issue).
- [ ] Enhancement (adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

# Checklist

Please ensure that all boxes are checked before indicating that a pull request is ready for review.

- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have deleted all non-relevant text in this pull request template.

### CODE REVIEW

**Review by d33bs — COMMENTED** [review]
Nice changes! Generally I thought your changes looked good. I did have questions regarding the additional files / thoughts below and wanted to get your input. Thanks in advance!

- Would it make sense to update the Python version in `.readthedocs.yml`?
- I think we might be able to bump the version of pre-commit in `requirements-dev.yml` to v3.x.x as per comments in #273 (there are also other steps @kenibrewer mentions which may need attention regarding the devcontainer files).
- Should we set a reminder or create a new issue for Python 3.8 EoL (October 2024 sometime)?

**Comment by gwaybio** [comment]
> Would it make sense to update the Python version in .readthedocs.yml?

Yep, I will add

> I think we might be able to bump the version of pre-commit in requirements-dev.yml to v3.x.x as per comments in
https://github.com/cytomining/pycytominer/issues/273 (there are also other steps @kenibrewer mentions which may need attention regarding the devcontainer files).

Thanks for pointing to this issue! I missed this. Will review and make corresponding changes here.

> Should we set a reminder or create a new issue for Python 3.8 EoL (October 2024 sometime)?

I think this is optional.

**Comment by gwaybio** [comment]
Thanks for the review @d33bs ! This is ready for another round

**Review by d33bs — APPROVED** [review]
Thanks for addressing the comments @gwaybio - LGTM!

**Pull request merged**
