### PR TITLE
Updating `__about__.py` version and fixing pyPI upload action

### PR DESCRIPTION
**Pull request by gwaybio**
# Description

Bumping the `__about__.py` version, which fixes the pyPI upload action. I also needed to set `skip_existing=True` in the github action file.

Related to #207 

## What is the nature of your change?

- [x] Bug fix (fixes an issue).
- [ ] Enhancement (adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

# Checklist

Please ensure that all boxes are checked before indicating that a pull request is ready for review.

- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have deleted all non-relevant text in this pull request template.

### CODE REVIEW

**Comment by gwaybio** [comment]
I also removed the author and author email tags in the setup.py

**Comment by gwaybio** [comment]
@staylorx - can you give a quick peek to see if this looks ok to you? I ask you specifically b/c you added the automatic pyPI upload in #188 . Thanks!

**Comment by staylorx** [comment]
Hey @gwaybio, sorry late on this. This looks okay to me. Thanks!

**Comment by gwaybio** [comment]
Perfect, thanks

**Pull request merged**
