### PR TITLE
Chore: Clarified pip install instructions

### LINKED ISSUE #253: pip install git+git isn't working
Hi, I's trying to install pycytominer though```pip install git+git://github.com/cytomining/pycytominer``` and isn't working for me, 

```
> pip install git+git://github.com/cytomining/pycytominer
Collecting git+git://github.com/cytomining/pycytominer
  Cloning git://github.com/cytomining/pycytominer to /private/var/folders/3z/k52fjt715kj7bxy2pz0fv_340000gq/T/pip-req-build-ps327vd5
  Running command git clone --filter=blob:none --quiet git://github.com/cytomining/pycytominer /private/var/folders/3z/k52fjt715kj7bxy2pz0fv_340000gq/T/pip-req-build-ps327vd5
  fatal: unable to connect to github.com:
  github.com[0: 140.82.114.4]: errno=Operation timed out

  error: subprocess-exited-with-error
```
so I changed to 

```pip install git+https://github.com/cytomining/pycytominer```

And worked!

### PR DESCRIPTION
**Pull request by kenibrewer**
# Description

Clarification in documentation that resolves #253 and will better support anonymous installs of pycytominer from users unfamiliar with the syntax of `pip install git+` commands. 

## What is the nature of your change?

- [x] Bug fix (fixes an issue).
- [ ] Enhancement (adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

# Checklist

Please ensure that all boxes are checked before indicating that a pull request is ready for review.

- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have deleted all non-relevant text in this pull request template.

### CODE REVIEW

**Comment by danodonovan** [comment]
This change is preferred by PyPI

> The use of git, git+git, and git+http schemes is discouraged. The former two use the Git Protocol, which lacks authentication, and HTTP is insecure due to lack of TLS based encryption.

https://pip.pypa.io/en/stable/topics/vcs-support/

**Comment by kenibrewer** [comment]
@gwaybio Could I get a review on this PR?

**Review by gwaybio — CHANGES_REQUESTED** [review]
We're currently working toward a version 1 release, which will change the instructions in the README. For us to merge a pip install clarification, I think it is worth removing the pip + git install commands in favor of pip alone (also adding reference to [pycytominer on conda](https://anaconda.org/conda-forge/pycytominer)) and all other references to pycytominer still being in beta.

**Comment by kenibrewer** [comment]
Superseded by #289

**Pull request closed without merging**
