### PR TITLE
Adding open source guideline documents

### PR DESCRIPTION
**Pull request by gwaygenomics**
Adding information on how to contribute to this codebase.

We are planning on discussing this in more detail at a meeting tomorrow. I will summarize the meeting here, before merging.

### CODE REVIEW

**Review by niranjchandrasekaran — APPROVED** [review]
Looks great!

**Comment by gwaygenomics** [comment]
Thanks @niranjchandrasekaran - adding @shntnu and @AnneCarpenter for their comments (or at least so that they're aware we're thinking about future contributions!)

**Comment by AnneCarpenter** [comment]
LGTM! Note that we have a set of guidelines we use for other Carpenter lab projects but if this is a Way lab project and you prefer your flavors of these docs, that is great!

Related, you can use "http://broad.io/EthicsReporting" as in here, if it is appropriate:
https://github.com/CellProfiler/CellProfiler/blob/master/CONDUCT

**Comment by gwaygenomics** [comment]
FWIW I'm still viewing this as a "cytominer" product with an open source contribution model. Although I do think that the guidelines we establish here should allow for flexibility in assigning repo maintainers, which will likely not always be me. I suppose I should capture this somewhere in the text.

Also, I found the code of conduct link to code covenant from the CellProfiler repo! (CellProfiler uses v1.4, I add, and modify slightly, v2.0)

**Comment by gwaygenomics** [comment]
I added notes about the pull request process and merge criteria in 33f1894c5610c96458ead11a77eeb6da66cd1b3f

I also added a CODEOWNERS file ([which will automatically request reviews from project maintainers](https://github.blog/2017-07-06-introducing-code-owners/)). @niranjchandrasekaran - would you like to be on this file somewhere?

> We are planning on discussing this in more detail at a meeting tomorrow. I will summarize the meeting here, before merging.

We opted to not have a meeting and instead outline any thoughts here. It's possible there aren't any! Given the PR is already approved, I'll merge next week to give time for comments.

**Review by shntnu — APPROVED** [review]
I skimmed very quickly and it looks great already!

**Comment by niranjchandrasekaran** [comment]
@gwaygenomics 
>  would you like to be on this file somewhere?
If this is for the purpose of requesting PR review feel free to add me to all the categories.

Regarding the reviewing process of my PR (#129), I thought it was great! Your guidelines in this PR will likely make the process even better.

**Comment by gwaygenomics** [comment]
> If this is for the purpose of requesting PR review feel free to add me to all the categories.

Awesome, will do! You will be automatically "requested to review" when any pull request is triggered. 

🤔 I probably should add merge instructions to this PR now.... I think we _both_ don't need to approve, one maintainer approval is sufficient IMO

**Pull request merged**
