### PR TITLE
ci(dependabot): enable auto poetry updates

### PR DESCRIPTION
**Pull request by d33bs**
# Description

This PR focuses on long-term sustainability for this project by enabling Dependabot to automatically update the Poetry lockfile. Normally this is a task which must be performed manually. By enabling this change we can have Dependabot automatically update the dependency references (which still fall into the constraints of the `pyproject.toml` file).

Thanks for any feedback!

## What is the nature of your change?

- [ ] Bug fix (fixes an issue).
- [x] Enhancement (adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

# Checklist

Please ensure that all boxes are checked before indicating that a pull request is ready for review.

- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have deleted all non-relevant text in this pull request template.

### CODE REVIEW

**Review by gwaybio — APPROVED** [review]

**Review by kenibrewer — CHANGES_REQUESTED** [review]
@d33bs Can we apply a [groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) policy that will put all non-major pip updates into a single dependabot PR? 

Otherwise, dependabot opens a ton of PRs that are a hassle to merge individually. 

Also, what are your thoughts about having the interval be monthly instead of weekly?

**Comment by d33bs** [comment]
Thanks @gwaybio and @kenibrewer, addressing the questions below:

> @d33bs Can we apply a [groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) policy that will put all non-major pip updates into a single dependabot PR?
> Otherwise, dependabot opens a ton of PRs that are a hassle to merge individually.

I don't have as much experience with this setting and will move forward with it as you mention. I'm cautious about this generally as I'd like to see isolated updates where possible to avoid dependency management chaos through the form of troubleshooting otherwise mysterious relationships when they're all combined in one spot. That said, I don't have any evidence this would happen here (just a feeling), so let's see how it goes with grouping!

> Also, what are your thoughts about having the interval be monthly instead of weekly?

Sounds good, let's move forward with monthly updates.

**Review by kenibrewer — APPROVED** [review]
Re grouping, I think the testing will hopefully catch any weirdness and let us investigate before getting merged. But if it causes problems we can definitely go back to individual PRS.

Thanks!

**Comment by d33bs** [comment]
Thanks @kenibrewer ! Merging this in.

**Pull request merged**
